# Generated by Django 4.2.30 on 2026-08-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('caps', 'Caps'), ('shorts', 'Shorts'), ('girl-shorts', 'Girl Shorts'), ('socks', 'Socks'), ('bucket-hats', 'Bucket Hats'), ('skirts', 'Skirts'), ('tops', 'Tops'), ('vest', 'Vest'), ('shirts', 'Shirts'), ('durags-wave-caps', 'Durags & Wave Caps'), ('windbreaker-track-pants', 'Windbreaker Track Pants'), ('tees', 'Tees'), ('graphic-tees', 'Graphic Tees'), ('varsity-jackets', 'Varsity Jackets'), ('puffer-jackets', 'Puffer Jackets'), ('jerseys', 'Jerseys'), ('hoodies', 'Hoodies'), ('zipper-hoodies', 'Zipper Hoodies')], default='shirts', max_length=30),
        ),
    ]
